### ISSUE TITLE
Py3k support

### ISSUE THREAD

**Issue by Mause** [epmoyer/ipy_table#9]
As best I can tell, it amounts to changing the single print statement to the print function, with an appropriate import from `__future__`, and swapping out `xrange` for `range`.

Or perhaps simply enabling the 2to3 tool in setup.py

**Comment by epmoyer** [comment]
Dominic,

Thanks! The current alpha build (``1.15.0a``) now has Travis integration (and tests, finally :) ), and is passing on 2.7, 3.3, 3.4, 3.5, and 3.6

I ended up using [six](https://pythonhosted.org/six/) , changing ``xrange`` to ``range`` (as you'd suggested), and resolving some NumPy related type naming differences.

 19cf72a

Cheers!
